version: '3.8'
services:
  desktop-authenticator:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - NODE_ENV=development
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri # For GPU acceleration 